package server.models;

import java.util.Objects;

/**
 * The AuthToken class is used by the server to keep track of users who are logged in and playing games. New AuthTokens are generated by the DataAccess class whenever a user logs in. AuthTokens are connected with usernames.
 */
public class AuthToken {
    String authToken;
    String username;

    public AuthToken(String authToken, String username) {
        this.authToken = authToken;
        this.username = username;
    }

    public String getAuthToken() {
        return authToken;
    }

    public String getUsername() {
        return username;
    }

    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        AuthToken otherAuthToken = (AuthToken) o;
        if (authToken == null ^ otherAuthToken.authToken == null) return false;
        if (username == null ^ otherAuthToken.username == null) return false;
        return (authToken != null && authToken.equals(otherAuthToken.authToken))
                && (username != null && username.equals(otherAuthToken.username));
    }
}
