package server.models;

/**
 * The AuthToken class is used by the server to keep track of users who are logged in and playing games. New AuthTokens are generated by the DataAccess class whenever a user logs in. AuthTokens are connected with usernames.
 */
public class AuthToken {
    /**
     * The string token. Used by the authTokens map in the DataAccess class as the key to storing all AuthTokens.
     */
    String authToken;
    /**
     * The username that's connected to the AuthToken (The user that's logged in)
     */
    String username;

    public AuthToken(String authToken, String username) {
        this.authToken = authToken;
        this.username = username;
    }

    public String getAuthToken() {
        return authToken;
    }

    public String getUsername() {
        return username;
    }

    public void setAuthToken(String authToken) {
        this.authToken = authToken;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}
